name: luminus_api
description: A library for Dart developers who's in need of LumiNUS API.
version: 0.1.4
homepage: https://github.com/fluminus/luminus_api
author: Tan Yuanhong <leotan.yh@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
 dotenv: ^1.0.0
 dio: ^2.1.3
 cookie_jar: ^1.0.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
