name: luminus_api
description: A library for Dart developers who's in need of LumiNUS API. 
  Including automated authentication and data abstractions for API responses.
version: 0.2.2
homepage: https://github.com/fluminus/luminus_api
author: Tan Yuanhong <leotan.yh@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
 dio: ^2.1.3
 cookie_jar: ^1.0.0
 convert: ^2.1.1
 http: ^0.12.0+2
 html: ^0.14.0+2
 meta: ^1.1.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  dotenv: ^1.0.0
